### ISSUE TITLE
Calendar is not popping up.

### ISSUE THREAD

**Issue by 13x54n** [13x54n/momo2go#2]
on delivery time change, it's supposed to open the calendar but it's not working.

**Comment by kyojurocode** [comment]
Hey, 
I came across your repository and I'm interested in contributing to the project. I noticed the issueand I would like to work on it. Could you please provide more details or guidance on how I can get started?

**Comment by 13x54n** [comment]
Hi, i just saw the comment, I'll be guiding you today midnight cause I'm going to work rn.

**Comment by kyojurocode** [comment]
Okay, cool
